/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package QuizGUI;

/**
 *
 * @author aamir7110
 */
public class QuizGUI extends javax.swing.JFrame {
    
    int correct = 0;
    int incorrect = 0;
    int progress = 1;
    double percent = 0;
    String answer;
    
    

    /**
     * Creates new form QuizGUI
     */
    public QuizGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        quizTitle = new javax.swing.JLabel();
        InstructionLabel = new javax.swing.JLabel();
        letterALabel = new javax.swing.JLabel();
        letterBLabel = new javax.swing.JLabel();
        letterCLabel = new javax.swing.JLabel();
        QuestionLabel = new javax.swing.JLabel();
        AnswerALabel = new javax.swing.JLabel();
        AnswerBLabel = new javax.swing.JLabel();
        AnswerCLabel = new javax.swing.JLabel();
        Answerbutton = new javax.swing.JButton();
        inputTextfield = new javax.swing.JTextField();
        CorrectLabel = new javax.swing.JLabel();
        Incorrectlabel = new javax.swing.JLabel();
        Percentlabel = new javax.swing.JLabel();
        Progressionlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(82, 121, 255));

        quizTitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        quizTitle.setText("Multiple Choice Quiz");

        InstructionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InstructionLabel.setText("To Answer A Question Type In The Letter In The Text Field");

        letterALabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        letterALabel.setText("A:");

        letterBLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        letterBLabel.setText("B:");

        letterCLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        letterCLabel.setText("C:");

        QuestionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QuestionLabel.setText("Do You Understand The Instructions?");

        AnswerALabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AnswerALabel.setText("Yes!");

        AnswerBLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AnswerBLabel.setText("No");

        AnswerCLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AnswerCLabel.setText("I Cant Read");

        Answerbutton.setText("Answer");
        Answerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerbuttonActionPerformed(evt);
            }
        });

        CorrectLabel.setText("Correct:0");

        Incorrectlabel.setText("Incorrect:0");

        Percentlabel.setText("Percentage:0%");

        Progressionlabel.setText("Question 1/5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterBLabel)
                                    .addComponent(letterALabel))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(letterCLabel)
                                .addGap(54, 54, 54)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AnswerALabel)
                            .addComponent(quizTitle)
                            .addComponent(AnswerBLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AnswerCLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Percentlabel)
                                .addGap(24, 24, 24))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CorrectLabel)
                            .addComponent(InstructionLabel)
                            .addComponent(Incorrectlabel))))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Answerbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputTextfield))
                        .addGap(162, 162, 162)
                        .addComponent(Progressionlabel)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(QuestionLabel)
                        .addGap(186, 186, 186))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InstructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuestionLabel)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letterALabel)
                    .addComponent(AnswerALabel)
                    .addComponent(CorrectLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letterBLabel)
                    .addComponent(AnswerBLabel)
                    .addComponent(Incorrectlabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letterCLabel)
                    .addComponent(AnswerCLabel)
                    .addComponent(Percentlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(inputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Answerbutton)
                    .addComponent(Progressionlabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnswerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerbuttonActionPerformed
        // TODO add your handling code here:
        //Question 1
        answer = inputTextfield.getText();
        progress = progress + 1;
        if(progress ==1){
        if(answer.equals("a")||(answer.equals("A"))){
            correct = correct + 1;
            
            
            CorrectLabel.setText("Correct:"+correct);
            Progressionlabel.setText("Question"+progress+"/5");
            
            
        }else{
           incorrect = incorrect + 1;
           
            Incorrectlabel.setText("Incorrect:"+incorrect);
            Progressionlabel.setText("Question"+progress+"/5");
            
        }
        }
        //Question 2
        if(progress ==2){
            
            QuestionLabel.setText("How Many Ants Does It Take To Make An Apple Pie?");
            AnswerALabel.setText("65478");
            AnswerBLabel.setText("Atleast 4");
            AnswerCLabel.setText("1");
            
            inputTextfield.setText("");
            
            answer =inputTextfield.getText();
            
            if(answer.equals("b")||(answer.equals("B"))){
                correct = correct + 1;
                
            
            CorrectLabel.setText("Correct:"+correct);
            Progressionlabel.setText("Question"+progress+"/5");
            inputTextfield.setText(null);
            }
            else{
                incorrect = incorrect + 1;
               
                Incorrectlabel.setText("Incorrect:"+incorrect);
                Progressionlabel.setText("Question"+progress+"/5");
                inputTextfield.setText(null);
            }
        }
        //Question 3
        if(progress ==3){
            QuestionLabel.setText("Are You Wearing Shoes?");
            AnswerALabel.setText("No");
            AnswerBLabel.setText("What Are Shoes");
            AnswerCLabel.setText("Yes");
            
            answer =inputTextfield.getText();
            
            if(answer.equals("c")||(answer.equals("C"))){
                correct = correct + 1;
               
            
            CorrectLabel.setText("Correct:"+correct);
            Progressionlabel.setText("Question"+progress+"/5");
            inputTextfield.setText("");
            }
            else{
                incorrect = incorrect + 1;
               
                Incorrectlabel.setText("Incorrect:"+incorrect);
                Progressionlabel.setText("Question"+progress+"/5");
                inputTextfield.setText("");
            }
        }
        //question 4
        if(progress ==4){
            QuestionLabel.setText("How long does it take a potato to grow into a cow?");
            AnswerALabel.setText("Like 5 Days");
            AnswerBLabel.setText("I cant, its a potato");
            AnswerCLabel.setText("Despacito");
            
            answer =inputTextfield.getText();
            
            if(answer.equals("a")||(answer.equals("A"))){
                correct = correct + 1;
               
            
            CorrectLabel.setText("Correct:"+correct);
            Progressionlabel.setText("Question"+progress+"/5");
            inputTextfield.setText("");
            }
            else{
                incorrect = incorrect + 1;
               
                Incorrectlabel.setText("Incorrect:"+incorrect);
                Progressionlabel.setText("Question"+progress+"/5");
                inputTextfield.setText("");
            }
    }//GEN-LAST:event_AnswerbuttonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnswerALabel;
    private javax.swing.JLabel AnswerBLabel;
    private javax.swing.JLabel AnswerCLabel;
    private javax.swing.JButton Answerbutton;
    private javax.swing.JLabel CorrectLabel;
    private javax.swing.JLabel Incorrectlabel;
    private javax.swing.JLabel InstructionLabel;
    private javax.swing.JLabel Percentlabel;
    private javax.swing.JLabel Progressionlabel;
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JTextField inputTextfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel letterALabel;
    private javax.swing.JLabel letterBLabel;
    private javax.swing.JLabel letterCLabel;
    private javax.swing.JLabel quizTitle;
    // End of variables declaration//GEN-END:variables
}
